In [1]:
import pandas as pd 
import warnings
warnings.filterwarnings("ignore")
import numpy as np 
import nltk
from sklearn.model_selection import train_test_split
from nltk.corpus import stopwords
from collections import defaultdict
from sklearn.feature_extraction.text import CountVectorizer #tokenizes and counts words
from sklearn.feature_extraction.text import TfidfVectorizer #alternatively, use TfidfTransformer()
from sklearn import metrics
import requests
from sklearn.feature_selection import RFE, chi2
from scipy.spatial import distance
from pandas.core.frame import DataFrame
from nltk import FreqDist
from sklearn.metrics.pairwise import cosine_similarity
from gensim.matutils import kullback_leibler, jaccard, hellinger, sparse2full
import string
from scipy.stats import entropy
from numpy.linalg import norm
from scipy.spatial import distance
import spacy
from collections import Counter
import math
from math import log
from spacy.lang.el import Greek

In [5]:
df = pd.read_csv('C:/Users/Yifeng He/Desktop/graduated/2nd graduate semester/text analysist/Untitled Folder 1/NA28_11_09_11PM.csv', encoding = 'utf-16', sep = '\t')
df2 = pd.read_csv('C:/Users/Yifeng He/Desktop/graduated/2nd graduate semester/text analysist/Untitled Folder 1/SBL_11_09_11PM.csv', encoding = 'utf-16', sep = '\t')
df3 = pd.read_csv('C:/Users/Yifeng He/Desktop/graduated/2nd graduate semester/text analysist/Untitled Folder 1/Tyndale_11_09_11PM.csv', encoding = 'utf-16', sep = '\t')

In [6]:
nlp = spacy.load('el_core_news_md')

In [7]:
def cosine_text(text):
    pos_tag = []
    pos_num = []
    for t in text['Verse']:
        pos_tag.append(nlp(t))
    for m in pos_tag:
        pos_num.append([n.pos for n in m])
    return pos_num

In [8]:
def text_author(text):
    author_tag = []
    for t in text['Author']:
        author_tag.append(1)
    return author_tag

In [9]:
def text_author1(text):
    author_tag = []
    for t in Heb['Author']:
        author_tag.append(0)
    return author_tag

## NA28_Version_Analytics

In [10]:
Matthew = df[df.BookName == 'Mt']
Matthew['Author'] = 'Matthew'
Mark = df[df.BookName == 'Mk']
Mark['Author'] = 'Mark'
Luke = df[df.BookName == 'Lk']
Luke['Author'] = 'Luke'
John = df[df.BookName == 'Joh']
John['Author'] = 'John'
Acts = df[df.BookName == 'Apg']
Acts['Author'] = 'Luke'
Luke_Book = pd.concat([Luke,Acts],axis = 0)
James = df[df.BookName == 'Jak']
James['Author'] = 'James'
f_Peter = df[df.BookName == '1.Petr']
s_Peter = df[df.BookName == '2.Petr']
f_Peter['Author'] = 'Peter'
s_Peter['Author'] = 'Peter'
Peter_letter = pd.concat([f_Peter, s_Peter], axis = 0)

f_John = df[df.BookName == '1.Joh']
s_John = df[df.BookName == '2.Joh']
t_John = df[df.BookName == '3.Joh']
f_John['Author'] = 'John'
s_John['Author'] = 'John'
t_John['Author'] = 'John'
John_letter = pd.concat([f_John, s_John, t_John], axis = 0)

Jude = df[df.BookName == 'Jud']
Jude['Author'] = 'Jude'
Rev = df[df.BookName == 'Offb']
Rev['Author'] = 'John'
John_Book = pd.concat([John,John_letter,Rev],axis = 0)

In [11]:
Romans = df[df.BookName == 'RÃ¶m']
Romans['Author'] = 'Paul'
f_cor = df[df.BookName == '1.Kor']
f_cor['Author'] = 'Paul'
s_cor = df[df.BookName == '2.Kor']
s_cor['Author'] = 'Paul'
Gal = df[df.BookName == 'Gal']
Gal['Author'] = 'Paul'
Eph = df[df.BookName == 'Eph']
Eph['Author'] = 'Paul'
Phi = df[df.BookName == 'Phil']
Phi['Author'] = 'Paul'
Col = df[df.BookName == 'Kol']
Col['Author'] = 'Paul'
f_the = df[df.BookName == '1.Thess']
f_the['Author'] = 'Paul'
s_the = df[df.BookName == '2.Thess']
s_the['Author'] = 'Paul'
f_tim = df[df.BookName == '1.Tim']
f_tim['Author'] = 'Paul'
s_tim = df[df.BookName == '2.Tim']
s_tim['Author'] = 'Paul'
Titus = df[df.BookName == 'Tit']
Titus['Author'] = 'Paul'
Philemon = df[df.BookName == 'Phlm']
Philemon['Author'] = 'Paul'
Paul_letters = pd.concat([Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon],axis = 0)
Heb = df[df.BookName == 'heb']
Heb['Author'] = 'Paul?'

In [12]:
g1 = cosine_text(Matthew)
g2 = cosine_text(Mark)
g3 = cosine_text(Luke)
g4 = cosine_text(John)
acts = cosine_text(Acts)
rms = cosine_text(Romans)
fcor = cosine_text(f_cor)
scor = cosine_text(s_cor)
gal = cosine_text(Gal)
eph = cosine_text(Eph)
phi = cosine_text(Phi)
col = cosine_text(Col)
fthe = cosine_text(f_the)
sthe = cosine_text(s_the)
ftim = cosine_text(f_tim)
stim = cosine_text(s_tim)
titus = cosine_text(Titus)
philemon = cosine_text(Philemon)
jams = cosine_text(James)
fpet = cosine_text(f_Peter)
spet = cosine_text(s_Peter)
fjohn = cosine_text(f_John)
sjohn = cosine_text(s_John)
tjohn = cosine_text(t_John.dropna())
jud = cosine_text(Jude)
rev = cosine_text(Rev)
hbr = cosine_text(Heb)

In [54]:
g11 = text_author(Matthew)
g21 = text_author(Mark)
g31 = text_author(Luke)
g41 = text_author(John)
acts1 = text_author(Acts)
rms1 = text_author(Romans)
fcor1 = text_author(f_cor)
scor1 = text_author(s_cor)
gal1 = text_author(Gal)
eph1 = text_author(Eph)
phi1 = text_author(Phi)
col1 = text_author(Col)
fthe1 = text_author(f_the)
sthe1 = text_author(s_the)
ftim1 = text_author(f_tim)
stim1 = text_author(s_tim)
titus1 = text_author(Titus)
philemon1 = text_author(Philemon)
jams1 = text_author(James)
fpet1 = text_author(f_Peter)
spet1 = text_author(s_Peter)
fjohn1 = text_author(f_John)
sjohn1 = text_author(s_John)
tjohn1 = text_author(t_John.dropna())
jud1 = text_author(Jude)
rev1 = text_author(Rev)
hbr1 = text_author1(Heb)

In [55]:

Matthew['Author_index'] = g11

Mark['Author_index'] = g21

Luke['Author_index'] = g31

John['Author_index'] = g41

Acts['Author_index'] = acts1

James['Author_index'] = jams1

f_Peter['Author_index'] = fpet1
s_Peter['Author_index'] = spet1

f_John['Author_index'] = fjohn1
s_John['Author_index'] = sjohn1
t_John['Author_index'] = tjohn1

Jude['Author_index'] = jud1

Rev['Author_index'] = rev1

Romans['Author_index'] = rms1

f_cor['Author_index'] = fcor1

s_cor['Author_index'] = scor1

Gal['Author_index'] = gal1

Eph['Author_index'] = eph1

Phi['Author_index'] = phi1

Col['Author_index'] = col1

f_the['Author_index'] = fthe1

s_the['Author_index'] = sthe1

f_tim['Author_index'] = ftim1

s_tim['Author_index'] = stim1

Titus['Author_index'] = titus1

Philemon['Author_index'] = philemon1


Heb['Author_index'] = hbr1

In [56]:

Matthew['Verse_index'] = g1

Mark['Verse_index'] = g2

Luke['Verse_index'] = g3

John['Verse_index'] = g4

Acts['Verse_index'] = acts

James['Verse_index'] = jams

f_Peter['Verse_index'] = fpet
s_Peter['Verse_index'] = spet

f_John['Verse_index'] = fjohn
s_John['Verse_index'] = sjohn
t_John['Verse_index'] = tjohn

Jude['Verse_index'] = jud

Rev['Verse_index'] = rev

Romans['Verse_index'] = rms

f_cor['Verse_index'] = fcor

s_cor['Verse_index'] = scor

Gal['Verse_index'] = gal

Eph['Verse_index'] = eph

Phi['Verse_index'] = phi

Col['Verse_index'] = col

f_the['Verse_index'] = fthe

s_the['Verse_index'] = sthe

f_tim['Verse_index'] = ftim

s_tim['Verse_index'] = stim

Titus['Verse_index'] = titus

Philemon['Verse_index'] = philemon


Heb['Verse_index'] = hbr

In [57]:
bible = pd.concat([Matthew,Mark,Luke,John,Acts,Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon,Heb,James,f_Peter,s_Peter,f_John,s_John,t_John,Jude,Rev],axis = 0)

In [60]:
bible.to_csv('na28withindex.csv', encoding = 'utf-16', sep = '\t', index = False)

## SBL_Version_Analytics

In [33]:
df2.BookName.unique()

array(['Mt', 'Mk', 'Lk', 'Jn', 'Ac', 'Ro', '1Co', '2Co', 'Ga', 'Eph',
       'Php', 'Col', '1Th', '2Th', '1Ti', '2Ti', 'Tit', 'Phm', 'Heb',
       'Jas', '1Pe', '2Pe', '1Jn', '2Jn', '3Jn', 'Jud', 'Re'],
      dtype=object)

In [61]:
Matthew = df2[df2.BookName == 'Mt']
Matthew['Author'] = 'Matthew'
Mark = df2[df2.BookName == 'Mk']
Mark['Author'] = 'Mark'
Luke = df2[df2.BookName == 'Lk']
Luke['Author'] = 'Luke'
John = df2[df2.BookName == 'Jn']
John['Author'] = 'John'
Acts = df2[df2.BookName == 'Ac']
Acts['Author'] = 'Luke'
Luke_Book = pd.concat([Luke,Acts],axis = 0)
James = df2[df2.BookName == 'Jas']
James['Author'] = 'James'
f_Peter = df2[df2.BookName == '1Pe']
s_Peter = df2[df2.BookName == '2Pe']
f_Peter['Author'] = 'Peter'
s_Peter['Author'] = 'Peter'
Peter_letter = pd.concat([f_Peter, s_Peter], axis = 0)

f_John = df2[df2.BookName == '1Jn']
s_John = df2[df2.BookName == '2Jn']
t_John = df2[df2.BookName == '3Jn']
f_John['Author'] = 'John'
s_John['Author'] = 'John'
t_John['Author'] = 'John'
John_letter = pd.concat([f_John, s_John, t_John], axis = 0)

Jude = df2[df2.BookName == 'Jud']
Jude['Author'] = 'Jude'
Rev = df2[df2.BookName == 'Re']
Rev['Author'] = 'John'
John_Book = pd.concat([John,John_letter,Rev],axis = 0)

In [62]:
Romans = df2[df2.BookName == 'Ro']
Romans['Author'] = 'Paul'
f_cor = df2[df2.BookName == '1Co']
f_cor['Author'] = 'Paul'
s_cor = df2[df2.BookName == '2Co']
s_cor['Author'] = 'Paul'
Gal = df2[df2.BookName == 'Ga']
Gal['Author'] = 'Paul'
Eph = df2[df2.BookName == 'Eph']
Eph['Author'] = 'Paul'
Phi = df2[df2.BookName == 'Php']
Phi['Author'] = 'Paul'
Col = df2[df2.BookName == 'Col']
Col['Author'] = 'Paul'
f_the = df2[df2.BookName == '1Th']
f_the['Author'] = 'Paul'
s_the = df2[df2.BookName == '2Th']
s_the['Author'] = 'Paul'
f_tim = df2[df2.BookName == '1Ti']
f_tim['Author'] = 'Paul'
s_tim = df2[df2.BookName == '2Ti']
s_tim['Author'] = 'Paul'
Titus = df2[df2.BookName == 'Tit']
Titus['Author'] = 'Paul'
Philemon = df2[df2.BookName == 'Phm']
Philemon['Author'] = 'Paul'
Paul_letters = pd.concat([Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon],axis = 0)
Heb = df2[df2.BookName == 'Heb']
Heb['Author'] = 'Paul?'

In [66]:
g1 = cosine_text(Matthew)
g2 = cosine_text(Mark)
g3 = cosine_text(Luke)
g4 = cosine_text(John)
acts = cosine_text(Acts)
rms = cosine_text(Romans)
fcor = cosine_text(f_cor)
scor = cosine_text(s_cor)
gal = cosine_text(Gal)
eph = cosine_text(Eph)
phi = cosine_text(Phi)
col = cosine_text(Col)
fthe = cosine_text(f_the)
sthe = cosine_text(s_the)
ftim = cosine_text(f_tim)
stim = cosine_text(s_tim)
titus = cosine_text(Titus)
philemon = cosine_text(Philemon)
jams = cosine_text(James)
fpet = cosine_text(f_Peter)
spet = cosine_text(s_Peter)
fjohn = cosine_text(f_John)
sjohn = cosine_text(s_John)
tjohn = cosine_text(t_John.dropna())
jud = cosine_text(Jude)
rev = cosine_text(Rev)
hbr = cosine_text(Heb)

In [67]:
g11 = text_author(Matthew)
g21 = text_author(Mark)
g31 = text_author(Luke)
g41 = text_author(John)
acts1 = text_author(Acts)
rms1 = text_author(Romans)
fcor1 = text_author(f_cor)
scor1 = text_author(s_cor)
gal1 = text_author(Gal)
eph1 = text_author(Eph)
phi1 = text_author(Phi)
col1 = text_author(Col)
fthe1 = text_author(f_the)
sthe1 = text_author(s_the)
ftim1 = text_author(f_tim)
stim1 = text_author(s_tim)
titus1 = text_author(Titus)
philemon1 = text_author(Philemon)
jams1 = text_author(James)
fpet1 = text_author(f_Peter)
spet1 = text_author(s_Peter)
fjohn1 = text_author(f_John)
sjohn1 = text_author(s_John)
tjohn1 = text_author(t_John.dropna())
jud1 = text_author(Jude)
rev1 = text_author(Rev)
hbr1 = text_author1(Heb)

In [69]:

Matthew['Author_index'] = g11

Mark['Author_index'] = g21

Luke['Author_index'] = g31

John['Author_index'] = g41

Acts['Author_index'] = acts1

James['Author_index'] = jams1

f_Peter['Author_index'] = fpet1
s_Peter['Author_index'] = spet1

f_John['Author_index'] = fjohn1
s_John['Author_index'] = sjohn1
t_John['Author_index'] = tjohn1

Jude['Author_index'] = jud1

Rev['Author_index'] = rev1

Romans['Author_index'] = rms1

f_cor['Author_index'] = fcor1

s_cor['Author_index'] = scor1

Gal['Author_index'] = gal1

Eph['Author_index'] = eph1

Phi['Author_index'] = phi1

Col['Author_index'] = col1

f_the['Author_index'] = fthe1

s_the['Author_index'] = sthe1

f_tim['Author_index'] = ftim1

s_tim['Author_index'] = stim1

Titus['Author_index'] = titus1

Philemon['Author_index'] = philemon1


Heb['Author_index'] = hbr1

In [70]:

Matthew['Verse_index'] = g1

Mark['Verse_index'] = g2

Luke['Verse_index'] = g3

John['Verse_index'] = g4

Acts['Verse_index'] = acts

James['Verse_index'] = jams

f_Peter['Verse_index'] = fpet
s_Peter['Verse_index'] = spet

f_John['Verse_index'] = fjohn
s_John['Verse_index'] = sjohn
t_John['Verse_index'] = tjohn

Jude['Verse_index'] = jud

Rev['Verse_index'] = rev

Romans['Verse_index'] = rms

f_cor['Verse_index'] = fcor

s_cor['Verse_index'] = scor

Gal['Verse_index'] = gal

Eph['Verse_index'] = eph

Phi['Verse_index'] = phi

Col['Verse_index'] = col

f_the['Verse_index'] = fthe

s_the['Verse_index'] = sthe

f_tim['Verse_index'] = ftim

s_tim['Verse_index'] = stim

Titus['Verse_index'] = titus

Philemon['Verse_index'] = philemon


Heb['Verse_index'] = hbr

In [71]:
bible = pd.concat([Matthew,Mark,Luke,John,Acts,Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon,Heb,James,f_Peter,s_Peter,f_John,s_John,t_John,Jude,Rev],axis = 0)

In [72]:
bible.to_csv('sblwithindex.csv', encoding = 'utf-16', sep = '\t', index = False)

## Tyndale_Version_Analytics

In [58]:
df3.BookName.unique()

array(['Matthew', 'Mark', 'Luke', 'John', 'Acts', 'Romans',
       '1Corinthians', '2Corinthians', 'Galatians', 'Ephesians',
       'Philippians', 'Colossians', '1Thessalonians', '2Thessalonians',
       '1Timothy', '2Timothy', 'Titus', 'Philemon', 'Hebrews', 'James',
       '1Peter', '2Peter', '1John', '2John', '3John', 'Jude',
       'Revelation'], dtype=object)

In [73]:
Matthew = df3[df3.BookName == 'Matthew']
Matthew['Author'] = 'Matthew'
Mark = df3[df3.BookName == 'Mark']
Mark['Author'] = 'Mark'
Luke = df3[df3.BookName == 'Luke']
Luke['Author'] = 'Luke'
John = df3[df3.BookName == 'John']
John['Author'] = 'John'
Acts = df3[df3.BookName == 'Acta']
Acts['Author'] = 'Luke'
Luke_Book = pd.concat([Luke,Acts],axis = 0)
James = df3[df3.BookName == 'Jamss']
James['Author'] = 'James'
f_Peter = df3[df3.BookName == '1Peter']
s_Peter = df3[df3.BookName == '2Peter']
f_Peter['Author'] = 'Peter'
s_Peter['Author'] = 'Peter'
Peter_letter = pd.concat([f_Peter, s_Peter], axis = 0)

f_John = df3[df3.BookName == '1John']
s_John = df3[df3.BookName == '2John']
t_John = df3[df3.BookName == '3John']
f_John['Author'] = 'John'
s_John['Author'] = 'John'
t_John['Author'] = 'John'
John_letter = pd.concat([f_John, s_John, t_John], axis = 0)

Jude = df3[df3.BookName == 'Jude']
Jude['Author'] = 'Jude'
Rev = df3[df3.BookName == 'Revelation']
Rev['Author'] = 'John'
John_Book = pd.concat([John,John_letter,Rev],axis = 0)

In [74]:
Romans = df3[df3.BookName == 'Romans']
Romans['Author'] = 'Paul'
f_cor = df3[df3.BookName == '1Corinthians']
f_cor['Author'] = 'Paul'
s_cor = df3[df3.BookName == '2Corinthians']
s_cor['Author'] = 'Paul'
Gal = df3[df3.BookName == 'Galatians']
Gal['Author'] = 'Paul'
Eph = df3[df3.BookName == 'Ephesians']
Eph['Author'] = 'Paul'
Phi = df3[df3.BookName == 'Philippians']
Phi['Author'] = 'Paul'
Col = df3[df3.BookName == 'Colossians']
Col['Author'] = 'Paul'
f_the = df3[df3.BookName == '1Thessalonians']
f_the['Author'] = 'Paul'
s_the = df3[df3.BookName == '2Thessalonians']
s_the['Author'] = 'Paul'
f_tim = df3[df3.BookName == '1Timothy']
f_tim['Author'] = 'Paul'
s_tim = df3[df3.BookName == '2Timothy']
s_tim['Author'] = 'Paul'
Titus = df3[df3.BookName == 'Titus']
Titus['Author'] = 'Paul'
Philemon = df3[df3.BookName == 'Philemon']
Philemon['Author'] = 'Paul'
Paul_letters = pd.concat([Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon],axis = 0)
Heb = df3[df3.BookName == 'Hebrews']
Heb['Author'] = 'Paul?'

In [75]:
g1 = cosine_text(Matthew)
g2 = cosine_text(Mark)
g3 = cosine_text(Luke)
g4 = cosine_text(John)
acts = cosine_text(Acts)
rms = cosine_text(Romans)
fcor = cosine_text(f_cor)
scor = cosine_text(s_cor)
gal = cosine_text(Gal)
eph = cosine_text(Eph)
phi = cosine_text(Phi)
col = cosine_text(Col)
fthe = cosine_text(f_the)
sthe = cosine_text(s_the)
ftim = cosine_text(f_tim)
stim = cosine_text(s_tim)
titus = cosine_text(Titus)
philemon = cosine_text(Philemon)
jams = cosine_text(James)
fpet = cosine_text(f_Peter)
spet = cosine_text(s_Peter)
fjohn = cosine_text(f_John)
sjohn = cosine_text(s_John)
tjohn = cosine_text(t_John.dropna())
jud = cosine_text(Jude)
rev = cosine_text(Rev)
hbr = cosine_text(Heb)

In [76]:
g11 = text_author(Matthew)
g21 = text_author(Mark)
g31 = text_author(Luke)
g41 = text_author(John)
acts1 = text_author(Acts)
rms1 = text_author(Romans)
fcor1 = text_author(f_cor)
scor1 = text_author(s_cor)
gal1 = text_author(Gal)
eph1 = text_author(Eph)
phi1 = text_author(Phi)
col1 = text_author(Col)
fthe1 = text_author(f_the)
sthe1 = text_author(s_the)
ftim1 = text_author(f_tim)
stim1 = text_author(s_tim)
titus1 = text_author(Titus)
philemon1 = text_author(Philemon)
jams1 = text_author(James)
fpet1 = text_author(f_Peter)
spet1 = text_author(s_Peter)
fjohn1 = text_author(f_John)
sjohn1 = text_author(s_John)
tjohn1 = text_author(t_John.dropna())
jud1 = text_author(Jude)
rev1 = text_author(Rev)
hbr1 = text_author1(Heb)

In [77]:

Matthew['Author_index'] = g11

Mark['Author_index'] = g21

Luke['Author_index'] = g31

John['Author_index'] = g41

Acts['Author_index'] = acts1

James['Author_index'] = jams1

f_Peter['Author_index'] = fpet1
s_Peter['Author_index'] = spet1

f_John['Author_index'] = fjohn1
s_John['Author_index'] = sjohn1
t_John['Author_index'] = tjohn1

Jude['Author_index'] = jud1

Rev['Author_index'] = rev1

Romans['Author_index'] = rms1

f_cor['Author_index'] = fcor1

s_cor['Author_index'] = scor1

Gal['Author_index'] = gal1

Eph['Author_index'] = eph1

Phi['Author_index'] = phi1

Col['Author_index'] = col1

f_the['Author_index'] = fthe1

s_the['Author_index'] = sthe1

f_tim['Author_index'] = ftim1

s_tim['Author_index'] = stim1

Titus['Author_index'] = titus1

Philemon['Author_index'] = philemon1


Heb['Author_index'] = hbr1

In [78]:

Matthew['Verse_index'] = g1

Mark['Verse_index'] = g2

Luke['Verse_index'] = g3

John['Verse_index'] = g4

Acts['Verse_index'] = acts

James['Verse_index'] = jams

f_Peter['Verse_index'] = fpet
s_Peter['Verse_index'] = spet

f_John['Verse_index'] = fjohn
s_John['Verse_index'] = sjohn
t_John['Verse_index'] = tjohn

Jude['Verse_index'] = jud

Rev['Verse_index'] = rev

Romans['Verse_index'] = rms

f_cor['Verse_index'] = fcor

s_cor['Verse_index'] = scor

Gal['Verse_index'] = gal

Eph['Verse_index'] = eph

Phi['Verse_index'] = phi

Col['Verse_index'] = col

f_the['Verse_index'] = fthe

s_the['Verse_index'] = sthe

f_tim['Verse_index'] = ftim

s_tim['Verse_index'] = stim

Titus['Verse_index'] = titus

Philemon['Verse_index'] = philemon


Heb['Verse_index'] = hbr

In [79]:
bible = pd.concat([Matthew,Mark,Luke,John,Acts,Romans,f_cor,s_cor,Gal,Eph,Phi,Col,f_the,s_the,f_tim,s_tim,Titus,Philemon,Heb,James,f_Peter,s_Peter,f_John,s_John,t_John,Jude,Rev],axis = 0)

In [80]:
bible.to_csv('tyndalewithindex.csv', encoding = 'utf-16', sep = '\t', index = False)